// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vcommerce.Data;

#nullable disable

namespace Vcommerce.Data.Migrations
{
    [DbContext(typeof(VcommerceDbContext))]
    [Migration("20230817121340_AddingRelationshipForReviewsAndUsers")]
    partial class AddingRelationshipForReviewsAndUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostMainPictureUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PostMidSectionLeftImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PostMidSectionRightImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedPostGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RelatedPostGuid");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.BrandInfo.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Name = "Nike"
                        },
                        new
                        {
                            Id = new Guid("c7b6a459-6ce9-4f6f-ac0f-f92d61f17a1b"),
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("e9089772-5892-4f5b-8e3d-82ef55d1e4a3"),
                            Name = "Puma"
                        },
                        new
                        {
                            Id = new Guid("f4eedcda-6b05-434e-b9f9-22f5a7df981e"),
                            Name = "Under Armour"
                        },
                        new
                        {
                            Id = new Guid("af65433f-562e-4233-84fa-feac5b99c142"),
                            Name = "Reebok"
                        },
                        new
                        {
                            Id = new Guid("bda763c3-2e5b-4db9-9959-36f3a03daa8e"),
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = new Guid("0a64a7d4-7cc9-441e-b6d0-55d295f186f4"),
                            Name = "Vans"
                        },
                        new
                        {
                            Id = new Guid("b2d1ef3e-b42b-4ccb-a88e-51184e7d7da2"),
                            Name = "Converse"
                        },
                        new
                        {
                            Id = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Name = "Levi's"
                        },
                        new
                        {
                            Id = new Guid("fe806f53-78d7-4ac3-bc48-735da7ef15dd"),
                            Name = "Tommy Hilfiger"
                        },
                        new
                        {
                            Id = new Guid("a9b80144-68b2-4eb3-8c06-b98ed0c5b672"),
                            Name = "Ralph Lauren"
                        },
                        new
                        {
                            Id = new Guid("8d5121b9-097d-432c-b49a-ad582a3a71d2"),
                            Name = "Calvin Klein"
                        },
                        new
                        {
                            Id = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Name = "H&M"
                        },
                        new
                        {
                            Id = new Guid("7dee85d1-8681-40d4-93ed-b4702afade72"),
                            Name = "Zara"
                        },
                        new
                        {
                            Id = new Guid("c19542eb-7c8e-48e9-98a5-e7b5d5df43b9"),
                            Name = "GAP"
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Clothes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("NumberOfSales")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalePercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 1,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cool graphic print t-shirt for stylish men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Graphic Print Tee",
                            NumberOfSales = 57,
                            Price = 24.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 1,
                            Color = "White",
                            DateCreated = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Essential V-neck basic t-shirt for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's V-Neck Basic Tee",
                            NumberOfSales = 68,
                            Price = 19.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 4,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic striped polo shirt for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Striped Polo Shirt",
                            NumberOfSales = 60,
                            Price = 29.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            BrandId = new Guid("c7b6a459-6ce9-4f6f-ac0f-f92d61f17a1b"),
                            Category = 1,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Versatile crew neck t-shirt for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Crew Neck Tee",
                            NumberOfSales = 29,
                            Price = 21.95m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("e21d6efd-5049-490b-a4ba-799f5505518b"),
                            BrandId = new Guid("c7b6a459-6ce9-4f6f-ac0f-f92d61f17a1b"),
                            Category = 1,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish and comfortable Henley shirt for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Henley Shirt",
                            NumberOfSales = 27,
                            Price = 26.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("3a63ab3e-d7f0-4c42-b3b2-db6f068e3927"),
                            BrandId = new Guid("c7b6a459-6ce9-4f6f-ac0f-f92d61f17a1b"),
                            Category = 1,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable casual t-shirt for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Casual T-Shirt",
                            NumberOfSales = 22,
                            Price = 29.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("722baf22-98de-45c5-b3a1-76f1a2276a41"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 2,
                            Color = "White",
                            DateCreated = new DateTime(2023, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A formal dress shirt for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Formal Dress Shirt",
                            NumberOfSales = 93,
                            Price = 49.99m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("fa924b74-bb89-4fc6-a140-f2df792e1aa5"),
                            BrandId = new Guid("e9089772-5892-4f5b-8e3d-82ef55d1e4a3"),
                            Category = 3,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish slim-fit jeans for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Denim",
                            Name = "Men's Slim-Fit Jeans",
                            NumberOfSales = 77,
                            Price = 69.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b221d46f-12f4-4813-8909-927720615e53"),
                            BrandId = new Guid("e9089772-5892-4f5b-8e3d-82ef55d1e4a3"),
                            Category = 4,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic polo shirt for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Polo Shirt",
                            NumberOfSales = 54,
                            Price = 34.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("b6effa76-7c26-4cb5-b277-656e45675482"),
                            BrandId = new Guid("f4eedcda-6b05-434e-b9f9-22f5a7df981e"),
                            Category = 5,
                            Color = "Brown",
                            DateCreated = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish leather jacket for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Leather",
                            Name = "Men's Leather Jacket",
                            NumberOfSales = 42,
                            Price = 149.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("32d319e0-c6a4-46b1-82d9-240d7de9ad2c"),
                            BrandId = new Guid("f4eedcda-6b05-434e-b9f9-22f5a7df981e"),
                            Category = 6,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable hoodie for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Hoodie",
                            NumberOfSales = 38,
                            Price = 39.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("902c1a00-502c-40ab-8bbb-5a93d54674a2"),
                            BrandId = new Guid("f4eedcda-6b05-434e-b9f9-22f5a7df981e"),
                            Category = 7,
                            Color = "Charcoal",
                            DateCreated = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An elegant formal suit for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Wool",
                            Name = "Men's Formal Suit",
                            NumberOfSales = 26,
                            Price = 299.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("2d7a7984-dfb6-4c94-aff4-71047f676f96"),
                            BrandId = new Guid("f4eedcda-6b05-434e-b9f9-22f5a7df981e"),
                            Category = 8,
                            Color = "Olive",
                            DateCreated = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable cargo shorts for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Cargo Shorts",
                            NumberOfSales = 65,
                            Price = 44.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("6e7438c2-245e-42ef-86dd-43280eeee071"),
                            BrandId = new Guid("af65433f-562e-4233-84fa-feac5b99c142"),
                            Category = 9,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy V-neck sweater for men.",
                            Gender = 1,
                            IsOnSale = true,
                            Material = "Wool",
                            Name = "Men's V-Neck Sweater",
                            NumberOfSales = 26,
                            Price = 54.99m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("86b0240c-56cb-449f-b429-575f0937105c"),
                            BrandId = new Guid("af65433f-562e-4233-84fa-feac5b99c142"),
                            Category = 10,
                            Color = "Charcoal",
                            DateCreated = new DateTime(2023, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A versatile casual blazer for men.",
                            Gender = 1,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Casual Blazer",
                            NumberOfSales = 56,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("2ba9a727-d0c6-4a41-ae5b-3e8575ce6ef0"),
                            BrandId = new Guid("af65433f-562e-4233-84fa-feac5b99c142"),
                            Category = 11,
                            Color = "White",
                            DateCreated = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable and chic blouse for women.",
                            Gender = 2,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Women's Casual Blouse",
                            NumberOfSales = 32,
                            Price = 39.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("1234180a-cae7-4cf6-b237-a0d443b9c963"),
                            BrandId = new Guid("af65433f-562e-4233-84fa-feac5b99c142"),
                            Category = 12,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish floral sundress for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Rayon",
                            Name = "Women's Floral Sundress",
                            NumberOfSales = 6,
                            Price = 69.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("d3c02d65-dac9-4db7-b073-74630f92ee01"),
                            BrandId = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Category = 3,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trendy skinny jeans for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Denim",
                            Name = "Women's Skinny Jeans",
                            NumberOfSales = 28,
                            Price = 79.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("3db4321b-8228-45a2-b05a-6831e82039ea"),
                            BrandId = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Category = 9,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy knit sweater for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Wool",
                            Name = "Women's Knit Sweater",
                            NumberOfSales = 8,
                            Price = 54.99m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("7ee9866b-fd2b-4f64-8db0-f87c7bfae700"),
                            BrandId = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Category = 5,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish faux leather jacket for women.",
                            Gender = 2,
                            IsOnSale = false,
                            Material = "Faux Leather",
                            Name = "Women's Faux Leather Jacket",
                            NumberOfSales = 99,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("feec2a48-71cb-4377-93e1-c879d659698c"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 18,
                            Color = "Beige",
                            DateCreated = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fashionable wide-leg pants for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Polyester",
                            Name = "Women's Wide-Leg Pants",
                            NumberOfSales = 59,
                            Price = 64.95m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("36e19d2c-825b-431f-9390-5ab3ec07fb2f"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 10,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sophisticated formal blazer for women.",
                            Gender = 2,
                            IsOnSale = false,
                            Material = "Polyester",
                            Name = "Women's Formal Blazer",
                            NumberOfSales = 51,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("c57e8283-1e82-48bd-996e-705f66f6a3d2"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 13,
                            Color = "Purple",
                            DateCreated = new DateTime(2023, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A boho-style maxi skirt for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Rayon",
                            Name = "Women's Boho Maxi Skirt",
                            NumberOfSales = 81,
                            Price = 59.99m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("82bbe618-2b7e-4027-a83a-bfd55d85a3b5"),
                            BrandId = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Category = 13,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A trendy A-line midi skirt for women.",
                            Gender = 2,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Women's A-Line Midi Skirt",
                            NumberOfSales = 34,
                            Price = 49.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("206bdf4e-8a81-4b28-bcf8-68e9ed167209"),
                            BrandId = new Guid("8bdc7349-8182-4df5-9fd0-3a4770f3d1fc"),
                            Category = 13,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A graceful pleated maxi skirt for women.",
                            Gender = 2,
                            IsOnSale = false,
                            Material = "Chiffon",
                            Name = "Women's Pleated Maxi Skirt",
                            NumberOfSales = 6,
                            Price = 79.95m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f4cbc240-1a50-4b55-a244-4f75ecd87de8"),
                            BrandId = new Guid("d6a153bf-fb89-45be-8e1c-e33adc7766ff"),
                            Category = 1,
                            Color = "Yellow",
                            DateCreated = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cute and colorful t-shirt for kids.",
                            Gender = 3,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Cute T-Shirt",
                            NumberOfSales = 91,
                            Price = 19.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("d7bdce86-af37-46d8-9d80-1e0979afcfc8"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 18,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adorable denim overalls for adventurous kids.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Denim",
                            Name = "Kids' Denim Overalls",
                            NumberOfSales = 57,
                            Price = 34.95m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("554bc6c9-a5ff-4515-8d60-d4473fe3f506"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 12,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beautiful princess dress for little girls.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Satin",
                            Name = "Kids' Princess Dress",
                            NumberOfSales = 12,
                            Price = 49.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("820357c5-64d4-4682-b55b-b1710ec91c1b"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 9,
                            Color = "Red",
                            DateCreated = new DateTime(2023, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fun and cozy hoodie with cartoon characters for kids.",
                            Gender = 3,
                            IsOnSale = true,
                            Material = "Fleece",
                            Name = "Kids' Cartoon Hoodie",
                            NumberOfSales = 89,
                            Price = 29.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("0fc675d9-fb8c-486a-9c79-ce88bc5688c0"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 8,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable sporty shorts for active kids.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Polyester",
                            Name = "Kids' Sporty Shorts",
                            NumberOfSales = 93,
                            Price = 24.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 1,
                            Color = "Green",
                            DateCreated = new DateTime(2023, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cool graphic print t-shirt for stylish kids.",
                            Gender = 3,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Graphic Print Tee",
                            NumberOfSales = 54,
                            Price = 17.95m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 4,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic striped polo shirt for little preppy kids.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Striped Polo Shirt",
                            NumberOfSales = 7,
                            Price = 27.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("4df2f27b-788a-4eb4-8c1a-30b397d4a1aa"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 13,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cute and frilly ruffled skirt for little girls.",
                            Gender = 3,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Ruffled Skirt",
                            NumberOfSales = 14,
                            Price = 22.95m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("fe367f15-2491-4b35-b956-8b05b7ac7eda"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 18,
                            Color = "Khaki",
                            DateCreated = new DateTime(2023, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sturdy cargo pants for adventurous kids.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Cargo Pants",
                            NumberOfSales = 75,
                            Price = 34.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("94c233fa-0a62-4a3e-9140-f3010efedee2"),
                            BrandId = new Guid("b89987d5-80b1-4b0e-afb5-48db1ebf76e2"),
                            Category = 1,
                            Color = "Green",
                            DateCreated = new DateTime(2023, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fun and colorful cartoon printed shirt for kids.",
                            Gender = 3,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Cartoon Printed Shirt",
                            NumberOfSales = 71,
                            Price = 19.95m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClothingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClothingGuid");

                    b.ToTable("ClothesImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8833646-137a-48d8-9855-1c625d8ef643"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/male-black-oversized-basketball-graphic-print-t-shirt.jpg?alt=media&token=b6f87596-658f-40e6-82be-6c7d9c2fb0bc"
                        },
                        new
                        {
                            Id = new Guid("d614cb45-c21c-4fd5-98d2-cd4d5a4cd68a"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/tball-graphic-print-t-shirt.jpg?alt=media&token=0cd8cb68-f961-47e1-ab6a-20bf875c3533"
                        },
                        new
                        {
                            Id = new Guid("0e06329a-a98a-429a-855f-ce2441d0e137"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/tball-graphic-print-t-shirt.jpg?alt=media&token=0cd8cb68-f961-47e1-ab6a-20bf875c3533"
                        },
                        new
                        {
                            Id = new Guid("ad94db3b-3b94-4b59-af61-277369177ba9"),
                            ClothingGuid = new Guid("94c233fa-0a62-4a3e-9140-f3010efedee2"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/4.jpg?alt=media&token=302976de-afcf-4890-820b-e779a301b097"
                        },
                        new
                        {
                            Id = new Guid("92a26213-0630-4e7f-8a77-250ba2d50e12"),
                            ClothingGuid = new Guid("fe367f15-2491-4b35-b956-8b05b7ac7eda"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/EACHIN-Boys-Pants-Boys-Pants-Solid-Cargo-Pants-Teenage-Boy-Multi-Pocket-Trousers-Kids-Spring-Autumn.jpg?alt=media&token=c893e73d-39e5-4aa5-9d59-7b6dc656d53a"
                        },
                        new
                        {
                            Id = new Guid("c1c8f5b4-07d2-4427-a9b1-12c0fa7b3e30"),
                            ClothingGuid = new Guid("4df2f27b-788a-4eb4-8c1a-30b397d4a1aa"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/Untitled.jpg?alt=media&token=3cc125cf-3a85-4cfc-9129-a2ebaf5f4cd4"
                        },
                        new
                        {
                            Id = new Guid("044b520e-75a1-4c31-9f43-854674877114"),
                            ClothingGuid = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/lacoste-teen-boys-striped-polo-shirt-386596-2ecde85e16638564ddf8022cb8e3b7e992190f33.jpg?alt=media&token=0c0fbedd-181e-48d0-b37d-50ae7f9fee5f"
                        },
                        new
                        {
                            Id = new Guid("d141ef27-bc98-4962-8508-88be86616169"),
                            ClothingGuid = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/images.jpg?alt=media&token=b65a904a-0be8-464b-b6df-3f1e3dd24f4a"
                        },
                        new
                        {
                            Id = new Guid("61b86af5-4383-4c81-865e-3f62bb4d69b6"),
                            ClothingGuid = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/GUEST_de1d201a-9f6a-45c0-a832-c0d0176c03a7.jpg?alt=media&token=51bb66e9-cbaf-45d0-8149-2c473c858d18"
                        },
                        new
                        {
                            Id = new Guid("77908fd2-8b4e-450f-ac20-7ed79b26b096"),
                            ClothingGuid = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/Kids'%20Graphic%20Print%20Tee.jpg?alt=media&token=ed6e6aa4-d1fd-463c-aa14-4ebdd3f190ca"
                        },
                        new
                        {
                            Id = new Guid("f267a2bd-44cd-47a6-85de-6f49cf7ce531"),
                            ClothingGuid = new Guid("206bdf4e-8a81-4b28-bcf8-68e9ed167209"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/711CPySZUIL._AC_UY1000_.jpg?alt=media&token=1a95a798-6212-4d38-a2c8-4b3eb04ccf74"
                        },
                        new
                        {
                            Id = new Guid("1cfa4bd1-83d3-4112-bbba-d5020d1bf260"),
                            ClothingGuid = new Guid("82bbe618-2b7e-4027-a83a-bfd55d85a3b5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/GUEST_7c2c7453-493c-4794-8653-7de130c53eb9.jpg?alt=media&token=6f341a35-5fc4-46c9-aab8-8d03a42906c0"
                        },
                        new
                        {
                            Id = new Guid("c4660820-e2c7-4525-a8a9-a527b47473e4"),
                            ClothingGuid = new Guid("36e19d2c-825b-431f-9390-5ab3ec07fb2f"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/474305ef653fc6da70213cb4650f37e9.jpg?alt=media&token=f6efc379-f291-4d5e-a330-3f066b96d655"
                        },
                        new
                        {
                            Id = new Guid("ec06fb2a-5280-4189-9c3f-d4e7650d0075"),
                            ClothingGuid = new Guid("feec2a48-71cb-4377-93e1-c879d659698c"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A1.jpg?alt=media&token=8125f07a-62e1-40a7-8f25-aec9be4fdfa0"
                        },
                        new
                        {
                            Id = new Guid("3f907f64-5484-4ae7-9993-ef146df72a5d"),
                            ClothingGuid = new Guid("1234180a-cae7-4cf6-b237-a0d443b9c963"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A2.jpg?alt=media&token=b4ad3f80-55ae-4b1f-999b-a4458c8c806f"
                        },
                        new
                        {
                            Id = new Guid("3c54ea27-c1fa-4139-b23f-89aca54595d8"),
                            ClothingGuid = new Guid("2ba9a727-d0c6-4a41-ae5b-3e8575ce6ef0"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A3.jpg?alt=media&token=097fb988-3822-441f-93af-498f169a8c96"
                        },
                        new
                        {
                            Id = new Guid("d848baad-bed4-4917-8d82-a3867076a004"),
                            ClothingGuid = new Guid("6e7438c2-245e-42ef-86dd-43280eeee071"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A4.jpg?alt=media&token=8a04e1b2-bbc1-4e2f-805f-c0deba5bceb9"
                        },
                        new
                        {
                            Id = new Guid("6d04b609-635c-4f87-bc47-c16d4ffe0fe0"),
                            ClothingGuid = new Guid("2d7a7984-dfb6-4c94-aff4-71047f676f96"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A5.jpg?alt=media&token=875083db-6b93-47c6-a14d-b8c009c7017c"
                        },
                        new
                        {
                            Id = new Guid("de875b04-32cb-4145-b488-bd150935dc4f"),
                            ClothingGuid = new Guid("902c1a00-502c-40ab-8bbb-5a93d54674a2"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A6.jpg?alt=media&token=a0bc4a08-bf49-4414-929e-aae4ffbe888a"
                        },
                        new
                        {
                            Id = new Guid("a5148b39-d439-4b0f-a01e-9fed5be8ac9a"),
                            ClothingGuid = new Guid("32d319e0-c6a4-46b1-82d9-240d7de9ad2c"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A7.jpg?alt=media&token=af0ea87a-9947-429f-878e-1c135f2b2132"
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingSizes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClothingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SizeQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClothingId");

                    b.ToTable("ClothingSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27501ff8-61a2-47a0-940a-3d6d9ea5727d"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 5,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("a80c780d-aad0-4b56-af63-8e6a71702d37"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 4,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("ac4bc5d3-ab07-4b7f-932f-9ee5961a3456"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 3,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("89358937-df77-4ca5-8f00-74623de2f7b3"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 2,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("4b297e3a-41d2-44ab-85a7-63634d1b551b"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 7,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("794bbd55-edef-4f3d-8b18-9ce05b23e884"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 5,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("01d5a25f-8f0b-4ddb-a45c-d21c0980c7f3"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 4,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("f2e03459-e0a1-45ca-bfc3-0e835735aecf"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 6,
                            SizeQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("00b27860-dbd6-4f18-adfc-35726c458029"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 3,
                            SizeQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("34cc5743-6df1-43fa-a197-02a6c0f48701"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 3,
                            SizeQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("ff285dee-302e-4865-b87f-1ac93bcd2ea1"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 4,
                            SizeQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("2f62f9c3-32b1-4748-a821-5c889c0d6e0f"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 5,
                            SizeQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("67f1d9b5-85f9-4d43-92f0-bb2440f9fd80"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 6,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("a1326497-7be5-4807-90da-7e8405b0c9b0"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 6,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("26fff197-03ad-4178-844c-d368937b2948"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 3,
                            SizeQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("72f3ba85-bcd8-4f6f-8afb-04e0b3c257c4"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 4,
                            SizeQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("fe0e575f-78a6-4c5b-9eee-24030edf3849"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 7,
                            SizeQuantity = 25
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Collections.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedClothingIdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserPostedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClothingIdGuid");

                    b.HasIndex("UserPostedId");

                    b.ToTable("ClothingReviews");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.BlogPost", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Blog.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Vcommerce.Data.Models.Blog.BlogPost", "RelatedPost")
                        .WithMany("Comments")
                        .HasForeignKey("RelatedPostGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("RelatedPost");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Clothes", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.BrandInfo.Brand", "Brand")
                        .WithMany("Clothes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vcommerce.Data.Models.Collections.Collection", "Collection")
                        .WithMany("Clothes")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingImages", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Images")
                        .HasForeignKey("ClothingGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingSizes", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Sizes")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Review", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Reviews")
                        .HasForeignKey("RelatedClothingIdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", "UserPosted")
                        .WithMany()
                        .HasForeignKey("UserPostedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");

                    b.Navigation("UserPosted");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.BrandInfo.Brand", b =>
                {
                    b.Navigation("Clothes");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Clothes", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Collections.Collection", b =>
                {
                    b.Navigation("Clothes");
                });
#pragma warning restore 612, 618
        }
    }
}
