// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vcommerce.Data;

#nullable disable

namespace Vcommerce.Data.Migrations
{
    [DbContext(typeof(VcommerceDbContext))]
    [Migration("20230731201256_AddingPartialSeeding")]
    partial class AddingPartialSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostMainPictureUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PostMidSectionLeftImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PostMidSectionRightImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedPostGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RelatedPostGuid");

                    b.ToTable("PostComments");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Clothes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("NumberOfSales")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalePercentage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clothes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Brand = "CoolGuys",
                            Category = 1,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cool graphic print t-shirt for stylish men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Graphic Print Tee",
                            NumberOfSales = 90,
                            Price = 24.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Brand = "ClassicMan",
                            Category = 1,
                            Color = "White",
                            DateCreated = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Essential V-neck basic t-shirt for men.",
                            Gender = 1,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's V-Neck Basic Tee",
                            NumberOfSales = 68,
                            Price = 19.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Brand = "PreppyStyle",
                            Category = 4,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic striped polo shirt for men.",
                            Gender = 1,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Striped Polo Shirt",
                            NumberOfSales = 84,
                            Price = 29.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Brand = "CasualChic",
                            Category = 1,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Versatile crew neck t-shirt for men.",
                            Gender = 1,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Crew Neck Tee",
                            NumberOfSales = 82,
                            Price = 21.95m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("e21d6efd-5049-490b-a4ba-799f5505518b"),
                            Brand = "ModernMan",
                            Category = 1,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish and comfortable Henley shirt for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Henley Shirt",
                            NumberOfSales = 92,
                            Price = 26.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("3a63ab3e-d7f0-4c42-b3b2-db6f068e3927"),
                            Brand = "ABC",
                            Category = 1,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable casual t-shirt for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Casual T-Shirt",
                            NumberOfSales = 97,
                            Price = 29.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("722baf22-98de-45c5-b3a1-76f1a2276a41"),
                            Brand = "Elegant Attire",
                            Category = 2,
                            Color = "White",
                            DateCreated = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A formal dress shirt for men.",
                            Gender = 1,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Formal Dress Shirt",
                            NumberOfSales = 80,
                            Price = 49.99m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("fa924b74-bb89-4fc6-a140-f2df792e1aa5"),
                            Brand = "DenimStyle",
                            Category = 3,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stylish slim-fit jeans for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Denim",
                            Name = "Men's Slim-Fit Jeans",
                            NumberOfSales = 44,
                            Price = 69.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("b221d46f-12f4-4813-8909-927720615e53"),
                            Brand = "SportyLook",
                            Category = 4,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A classic polo shirt for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Polo Shirt",
                            NumberOfSales = 42,
                            Price = 34.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("b6effa76-7c26-4cb5-b277-656e45675482"),
                            Brand = "RuggedStyle",
                            Category = 5,
                            Color = "Brown",
                            DateCreated = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish leather jacket for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Leather",
                            Name = "Men's Leather Jacket",
                            NumberOfSales = 55,
                            Price = 149.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("32d319e0-c6a4-46b1-82d9-240d7de9ad2c"),
                            Brand = "UrbanWear",
                            Category = 6,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable hoodie for men.",
                            Gender = 1,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Men's Hoodie",
                            NumberOfSales = 16,
                            Price = 39.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("902c1a00-502c-40ab-8bbb-5a93d54674a2"),
                            Brand = "ClassyLook",
                            Category = 7,
                            Color = "Charcoal",
                            DateCreated = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An elegant formal suit for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Wool",
                            Name = "Men's Formal Suit",
                            NumberOfSales = 28,
                            Price = 299.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("2d7a7984-dfb6-4c94-aff4-71047f676f96"),
                            Brand = "AdventureGear",
                            Category = 8,
                            Color = "Olive",
                            DateCreated = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Durable cargo shorts for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Cargo Shorts",
                            NumberOfSales = 58,
                            Price = 44.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("6e7438c2-245e-42ef-86dd-43280eeee071"),
                            Brand = "CozyKnits",
                            Category = 9,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy V-neck sweater for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Wool",
                            Name = "Men's V-Neck Sweater",
                            NumberOfSales = 97,
                            Price = 54.99m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("86b0240c-56cb-449f-b429-575f0937105c"),
                            Brand = "SmartCasual",
                            Category = 10,
                            Color = "Charcoal",
                            DateCreated = new DateTime(2023, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A versatile casual blazer for men.",
                            Gender = 1,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Men's Casual Blazer",
                            NumberOfSales = 81,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("2ba9a727-d0c6-4a41-ae5b-3e8575ce6ef0"),
                            Brand = "ChicStyle",
                            Category = 11,
                            Color = "White",
                            DateCreated = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A comfortable and chic blouse for women.",
                            Gender = 2,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Women's Casual Blouse",
                            NumberOfSales = 40,
                            Price = 39.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("1234180a-cae7-4cf6-b237-a0d443b9c963"),
                            Brand = "GardenGlam",
                            Category = 12,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish floral sundress for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Rayon",
                            Name = "Women's Floral Sundress",
                            NumberOfSales = 39,
                            Price = 69.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("d3c02d65-dac9-4db7-b073-74630f92ee01"),
                            Brand = "DenimDivas",
                            Category = 3,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trendy skinny jeans for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Denim",
                            Name = "Women's Skinny Jeans",
                            NumberOfSales = 5,
                            Price = 79.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("3db4321b-8228-45a2-b05a-6831e82039ea"),
                            Brand = "CozyKnits",
                            Category = 9,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cozy knit sweater for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Wool",
                            Name = "Women's Knit Sweater",
                            NumberOfSales = 10,
                            Price = 54.99m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("7ee9866b-fd2b-4f64-8db0-f87c7bfae700"),
                            Brand = "UrbanChic",
                            Category = 5,
                            Color = "Black",
                            DateCreated = new DateTime(2023, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stylish faux leather jacket for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Faux Leather",
                            Name = "Women's Faux Leather Jacket",
                            NumberOfSales = 57,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("feec2a48-71cb-4377-93e1-c879d659698c"),
                            Brand = "FashionForward",
                            Category = 18,
                            Color = "Beige",
                            DateCreated = new DateTime(2023, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fashionable wide-leg pants for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Polyester",
                            Name = "Women's Wide-Leg Pants",
                            NumberOfSales = 15,
                            Price = 64.95m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("36e19d2c-825b-431f-9390-5ab3ec07fb2f"),
                            Brand = "ElegantAttire",
                            Category = 10,
                            Color = "Gray",
                            DateCreated = new DateTime(2023, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sophisticated formal blazer for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Polyester",
                            Name = "Women's Formal Blazer",
                            NumberOfSales = 61,
                            Price = 89.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("c57e8283-1e82-48bd-996e-705f66f6a3d2"),
                            Brand = "BohemianSpirit",
                            Category = 13,
                            Color = "Purple",
                            DateCreated = new DateTime(2023, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A boho-style maxi skirt for women.",
                            Gender = 2,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Rayon",
                            Name = "Women's Boho Maxi Skirt",
                            NumberOfSales = 60,
                            Price = 59.99m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("82bbe618-2b7e-4027-a83a-bfd55d85a3b5"),
                            Brand = "ModishMe",
                            Category = 13,
                            Color = "Navy",
                            DateCreated = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A trendy A-line midi skirt for women.",
                            Gender = 2,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Women's A-Line Midi Skirt",
                            NumberOfSales = 54,
                            Price = 49.99m,
                            Quantity = 0,
                            SalePercentage = 15m
                        },
                        new
                        {
                            Id = new Guid("206bdf4e-8a81-4b28-bcf8-68e9ed167209"),
                            Brand = "ElegantEve",
                            Category = 13,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A graceful pleated maxi skirt for women.",
                            Gender = 2,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Chiffon",
                            Name = "Women's Pleated Maxi Skirt",
                            NumberOfSales = 56,
                            Price = 79.95m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f4cbc240-1a50-4b55-a244-4f75ecd87de8"),
                            Brand = "HappyKids",
                            Category = 1,
                            Color = "Yellow",
                            DateCreated = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cute and colorful t-shirt for kids.",
                            Gender = 3,
                            IsNew = false,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Cute T-Shirt",
                            NumberOfSales = 64,
                            Price = 19.99m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("d7bdce86-af37-46d8-9d80-1e0979afcfc8"),
                            Brand = "LittleExplorers",
                            Category = 18,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Adorable denim overalls for adventurous kids.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Denim",
                            Name = "Kids' Denim Overalls",
                            NumberOfSales = 10,
                            Price = 34.95m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("554bc6c9-a5ff-4515-8d60-d4473fe3f506"),
                            Brand = "RoyalKids",
                            Category = 12,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A beautiful princess dress for little girls.",
                            Gender = 3,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Satin",
                            Name = "Kids' Princess Dress",
                            NumberOfSales = 22,
                            Price = 49.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("820357c5-64d4-4682-b55b-b1710ec91c1b"),
                            Brand = "FunTime",
                            Category = 9,
                            Color = "Red",
                            DateCreated = new DateTime(2023, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fun and cozy hoodie with cartoon characters for kids.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Fleece",
                            Name = "Kids' Cartoon Hoodie",
                            NumberOfSales = 21,
                            Price = 29.95m,
                            Quantity = 0,
                            SalePercentage = 20m
                        },
                        new
                        {
                            Id = new Guid("0fc675d9-fb8c-486a-9c79-ce88bc5688c0"),
                            Brand = "ActiveKids",
                            Category = 8,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comfortable sporty shorts for active kids.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Polyester",
                            Name = "Kids' Sporty Shorts",
                            NumberOfSales = 74,
                            Price = 24.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            Brand = "CoolKids",
                            Category = 1,
                            Color = "Green",
                            DateCreated = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cool graphic print t-shirt for stylish kids.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Graphic Print Tee",
                            NumberOfSales = 90,
                            Price = 17.95m,
                            Quantity = 0,
                            SalePercentage = 25m
                        },
                        new
                        {
                            Id = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            Brand = "PreppyKids",
                            Category = 4,
                            Color = "Blue",
                            DateCreated = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Classic striped polo shirt for little preppy kids.",
                            Gender = 3,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Striped Polo Shirt",
                            NumberOfSales = 63,
                            Price = 27.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("4df2f27b-788a-4eb4-8c1a-30b397d4a1aa"),
                            Brand = "CuteKids",
                            Category = 13,
                            Color = "Pink",
                            DateCreated = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A cute and frilly ruffled skirt for little girls.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = true,
                            Material = "Cotton",
                            Name = "Kids' Ruffled Skirt",
                            NumberOfSales = 82,
                            Price = 22.95m,
                            Quantity = 0,
                            SalePercentage = 10m
                        },
                        new
                        {
                            Id = new Guid("fe367f15-2491-4b35-b956-8b05b7ac7eda"),
                            Brand = "AdventureKids",
                            Category = 18,
                            Color = "Khaki",
                            DateCreated = new DateTime(2023, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sturdy cargo pants for adventurous kids.",
                            Gender = 3,
                            IsNew = false,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Cargo Pants",
                            NumberOfSales = 58,
                            Price = 34.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("94c233fa-0a62-4a3e-9140-f3010efedee2"),
                            Brand = "PlayfulKids",
                            Category = 1,
                            Color = "Green",
                            DateCreated = new DateTime(2023, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fun and colorful cartoon printed shirt for kids.",
                            Gender = 3,
                            IsNew = true,
                            IsOnSale = false,
                            Material = "Cotton",
                            Name = "Kids' Cartoon Printed Shirt",
                            NumberOfSales = 72,
                            Price = 19.95m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClothingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ClothingGuid");

                    b.ToTable("ClothesImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7db3b9c-d771-43a6-8e09-ad63d4fbb6f2"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/male-black-oversized-basketball-graphic-print-t-shirt.jpg?alt=media&token=b6f87596-658f-40e6-82be-6c7d9c2fb0bc"
                        },
                        new
                        {
                            Id = new Guid("c84a1aa2-a2d4-484a-b66d-11189d96cc86"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/tball-graphic-print-t-shirt.jpg?alt=media&token=0cd8cb68-f961-47e1-ab6a-20bf875c3533"
                        },
                        new
                        {
                            Id = new Guid("703918d4-a48f-4a3b-a510-098d1e83ce96"),
                            ClothingGuid = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/tball-graphic-print-t-shirt.jpg?alt=media&token=0cd8cb68-f961-47e1-ab6a-20bf875c3533"
                        },
                        new
                        {
                            Id = new Guid("9ccc6937-8d23-4e6d-8658-6b1bfa902507"),
                            ClothingGuid = new Guid("94c233fa-0a62-4a3e-9140-f3010efedee2"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/4.jpg?alt=media&token=302976de-afcf-4890-820b-e779a301b097"
                        },
                        new
                        {
                            Id = new Guid("9dbdfd86-1538-4fc0-875c-0ff6233bdb90"),
                            ClothingGuid = new Guid("fe367f15-2491-4b35-b956-8b05b7ac7eda"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/EACHIN-Boys-Pants-Boys-Pants-Solid-Cargo-Pants-Teenage-Boy-Multi-Pocket-Trousers-Kids-Spring-Autumn.jpg?alt=media&token=c893e73d-39e5-4aa5-9d59-7b6dc656d53a"
                        },
                        new
                        {
                            Id = new Guid("c72445ed-bf49-4600-9542-40809bb0d6d2"),
                            ClothingGuid = new Guid("4df2f27b-788a-4eb4-8c1a-30b397d4a1aa"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/Untitled.jpg?alt=media&token=3cc125cf-3a85-4cfc-9129-a2ebaf5f4cd4"
                        },
                        new
                        {
                            Id = new Guid("1a7e5d17-b62e-4139-8be6-983951cb8c6d"),
                            ClothingGuid = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/lacoste-teen-boys-striped-polo-shirt-386596-2ecde85e16638564ddf8022cb8e3b7e992190f33.jpg?alt=media&token=0c0fbedd-181e-48d0-b37d-50ae7f9fee5f"
                        },
                        new
                        {
                            Id = new Guid("d908183e-3e12-46d4-a3fa-b93feca50f8d"),
                            ClothingGuid = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/images.jpg?alt=media&token=b65a904a-0be8-464b-b6df-3f1e3dd24f4a"
                        },
                        new
                        {
                            Id = new Guid("d2467509-e320-4178-95f5-b9f588187601"),
                            ClothingGuid = new Guid("8ec859e8-597e-463b-8a4b-a485d4be7200"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/GUEST_de1d201a-9f6a-45c0-a832-c0d0176c03a7.jpg?alt=media&token=51bb66e9-cbaf-45d0-8149-2c473c858d18"
                        },
                        new
                        {
                            Id = new Guid("f86e87c2-2fc8-456b-878c-d5eb66a08725"),
                            ClothingGuid = new Guid("3b86cd7f-c0b6-487f-be42-a6f61f05b456"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/Kids'%20Graphic%20Print%20Tee.jpg?alt=media&token=ed6e6aa4-d1fd-463c-aa14-4ebdd3f190ca"
                        },
                        new
                        {
                            Id = new Guid("11b59d25-5505-4d09-801d-095a248f423b"),
                            ClothingGuid = new Guid("206bdf4e-8a81-4b28-bcf8-68e9ed167209"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/711CPySZUIL._AC_UY1000_.jpg?alt=media&token=1a95a798-6212-4d38-a2c8-4b3eb04ccf74"
                        },
                        new
                        {
                            Id = new Guid("73d4acfe-55b0-4a57-b1ef-56bfd581b615"),
                            ClothingGuid = new Guid("82bbe618-2b7e-4027-a83a-bfd55d85a3b5"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/GUEST_7c2c7453-493c-4794-8653-7de130c53eb9.jpg?alt=media&token=6f341a35-5fc4-46c9-aab8-8d03a42906c0"
                        },
                        new
                        {
                            Id = new Guid("85daab2d-093b-4045-99db-e71276288c31"),
                            ClothingGuid = new Guid("36e19d2c-825b-431f-9390-5ab3ec07fb2f"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/474305ef653fc6da70213cb4650f37e9.jpg?alt=media&token=f6efc379-f291-4d5e-a330-3f066b96d655"
                        },
                        new
                        {
                            Id = new Guid("ac238e7e-0a72-42f1-91fd-9cf694f1d928"),
                            ClothingGuid = new Guid("feec2a48-71cb-4377-93e1-c879d659698c"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A1.jpg?alt=media&token=8125f07a-62e1-40a7-8f25-aec9be4fdfa0"
                        },
                        new
                        {
                            Id = new Guid("615a54e6-892c-453e-ad8b-6c79912860c8"),
                            ClothingGuid = new Guid("1234180a-cae7-4cf6-b237-a0d443b9c963"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A2.jpg?alt=media&token=b4ad3f80-55ae-4b1f-999b-a4458c8c806f"
                        },
                        new
                        {
                            Id = new Guid("ab5e400f-851c-4202-9f33-9cc822975665"),
                            ClothingGuid = new Guid("2ba9a727-d0c6-4a41-ae5b-3e8575ce6ef0"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A3.jpg?alt=media&token=097fb988-3822-441f-93af-498f169a8c96"
                        },
                        new
                        {
                            Id = new Guid("a571b4af-62a4-4632-9f1f-b0b34eedb772"),
                            ClothingGuid = new Guid("6e7438c2-245e-42ef-86dd-43280eeee071"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A4.jpg?alt=media&token=8a04e1b2-bbc1-4e2f-805f-c0deba5bceb9"
                        },
                        new
                        {
                            Id = new Guid("d5a85635-ec43-4d4f-b685-c920523ab7d7"),
                            ClothingGuid = new Guid("2d7a7984-dfb6-4c94-aff4-71047f676f96"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A5.jpg?alt=media&token=875083db-6b93-47c6-a14d-b8c009c7017c"
                        },
                        new
                        {
                            Id = new Guid("bd1d3bfb-b423-4bf4-8c5a-df0a9165b205"),
                            ClothingGuid = new Guid("902c1a00-502c-40ab-8bbb-5a93d54674a2"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A6.jpg?alt=media&token=a0bc4a08-bf49-4414-929e-aae4ffbe888a"
                        },
                        new
                        {
                            Id = new Guid("2d845dcd-d2af-4280-abaa-905ac1056e50"),
                            ClothingGuid = new Guid("32d319e0-c6a4-46b1-82d9-240d7de9ad2c"),
                            ImageUrl = "https://firebasestorage.googleapis.com/v0/b/craftdemo-78c02.appspot.com/o/A7.jpg?alt=media&token=af0ea87a-9947-429f-878e-1c135f2b2132"
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingSizes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClothingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SizeQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClothingId");

                    b.ToTable("ClothingSizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffa4f988-ae37-47e6-a564-2a542e445784"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 5,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("9cd52004-231f-4465-a0e6-57510dff6ff9"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 4,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0bf6fcd-3061-4237-bfd9-85e9e8225dd6"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 3,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("8271cb0e-f3ad-47f0-9cbd-97271e9cd0c1"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 2,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("b8126a0d-314b-4eb4-9f25-277672de8e07"),
                            ClothingId = new Guid("283b533b-7ed3-4187-aa7f-cd8a52ed51a5"),
                            Size = 7,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("346aebc7-3a4c-41b2-aee4-e51f6b0afd14"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 5,
                            SizeQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("8a368aef-04a2-4033-8807-085925c75927"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 4,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("1f12a7c6-be3f-476b-a268-f8fe36cd81ba"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 6,
                            SizeQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("26eadb66-e6bf-468a-9f4c-eb8c02f304b5"),
                            ClothingId = new Guid("9f984cb7-39a8-4003-b9f2-b27ecd32842f"),
                            Size = 3,
                            SizeQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("fe6fa9d5-c3be-44d8-84e5-14da811067d9"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 3,
                            SizeQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("f963804b-78e4-411e-b923-388b2638b67c"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 4,
                            SizeQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("639e82ed-16d3-4e7a-b3bb-97a960609a50"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 5,
                            SizeQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("09dc8450-9d70-421c-8a51-60b1ffde5620"),
                            ClothingId = new Guid("0bbb0ce2-68f3-4cb1-b3a6-de68c6ad1fcd"),
                            Size = 6,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("321e8e75-ecb2-48d7-a786-c0386dcf3668"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 6,
                            SizeQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("066ec91f-d50e-4588-b592-fe2067b24486"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 3,
                            SizeQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("18000ae1-ed8c-44ff-8df8-7725ecf009c6"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 4,
                            SizeQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("4b881173-a452-4df7-aae4-d692e5dd64a8"),
                            ClothingId = new Guid("47b74821-1dd5-4aac-868a-aed6661017f6"),
                            Size = 7,
                            SizeQuantity = 25
                        });
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatedClothingIdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserPostedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedClothingIdGuid");

                    b.HasIndex("UserPostedId");

                    b.ToTable("ClothingReviews");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Blog.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("Vcommerce.Data.Models.Blog.BlogPost", "RelatedPost")
                        .WithMany("Comments")
                        .HasForeignKey("RelatedPostGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("RelatedPost");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingImages", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Images")
                        .HasForeignKey("ClothingGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.ClothingSizes", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Sizes")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Review", b =>
                {
                    b.HasOne("Vcommerce.Data.Models.Clothes", "RelatedClothing")
                        .WithMany("Reviews")
                        .HasForeignKey("RelatedClothingIdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vcommerce.Data.Models.Users.ApplicationUser", "UserPosted")
                        .WithMany()
                        .HasForeignKey("UserPostedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedClothing");

                    b.Navigation("UserPosted");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Blog.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Vcommerce.Data.Models.Clothes", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Sizes");
                });
#pragma warning restore 612, 618
        }
    }
}
